/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionId = IDL.Text;
export const CustomerInput = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
});
export const Weight = IDL.Record({
  'value' : IDL.Int,
  'unit' : IDL.Variant({ 'kilograms' : IDL.Null, 'grams' : IDL.Null }),
});
export const IngredientInput = IDL.Record({
  'lowStockThreshold' : Weight,
  'supplierName' : IDL.Text,
  'name' : IDL.Text,
  'quantity' : Weight,
  'costPricePerUnit' : IDL.Float64,
});
export const BowlSize = IDL.Variant({
  'large' : IDL.Null,
  'small' : IDL.Null,
  'medium' : IDL.Null,
});
export const RecipeIngredient = IDL.Record({
  'quantity' : Weight,
  'ingredientId' : IDL.Nat,
});
export const RecipeInput = IDL.Record({
  'name' : IDL.Text,
  'bowlSize' : BowlSize,
  'ingredients' : IDL.Vec(RecipeIngredient),
});
export const Ingredient = IDL.Record({
  'id' : IDL.Nat,
  'lowStockThreshold' : Weight,
  'supplierName' : IDL.Text,
  'name' : IDL.Text,
  'quantity' : Weight,
  'costPricePerUnit' : IDL.Float64,
});
export const Recipe = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'bowlSize' : BowlSize,
  'ingredients' : IDL.Vec(RecipeIngredient),
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'updatedAt' : IDL.Int,
  'address' : IDL.Text,
});
export const InventoryState = IDL.Record({
  'totalValue' : IDL.Float64,
  'ingredients' : IDL.Vec(Ingredient),
});

export const idlService = IDL.Service({
  'addCustomer' : IDL.Func([SessionId, CustomerInput], [IDL.Nat], []),
  'addIngredient' : IDL.Func([SessionId, IngredientInput], [], []),
  'addRecipe' : IDL.Func([SessionId, RecipeInput], [], []),
  'createSession' : IDL.Func([], [SessionId], []),
  'deleteCustomer' : IDL.Func([SessionId, IDL.Nat], [], []),
  'endSession' : IDL.Func([SessionId], [], []),
  'getAllIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
  'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
  'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getIngredient' : IDL.Func([IDL.Nat], [IDL.Opt(Ingredient)], ['query']),
  'getInventoryState' : IDL.Func([], [InventoryState], ['query']),
  'getLowStockIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
  'getRecipe' : IDL.Func([IDL.Nat], [IDL.Opt(Recipe)], ['query']),
  'isSessionActive' : IDL.Func([SessionId], [IDL.Bool], ['query']),
  'updateCustomer' : IDL.Func([SessionId, IDL.Nat, CustomerInput], [], []),
  'updateIngredient' : IDL.Func([SessionId, IDL.Nat, IngredientInput], [], []),
  'updateRecipe' : IDL.Func([SessionId, IDL.Nat, RecipeInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionId = IDL.Text;
  const CustomerInput = IDL.Record({
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
  });
  const Weight = IDL.Record({
    'value' : IDL.Int,
    'unit' : IDL.Variant({ 'kilograms' : IDL.Null, 'grams' : IDL.Null }),
  });
  const IngredientInput = IDL.Record({
    'lowStockThreshold' : Weight,
    'supplierName' : IDL.Text,
    'name' : IDL.Text,
    'quantity' : Weight,
    'costPricePerUnit' : IDL.Float64,
  });
  const BowlSize = IDL.Variant({
    'large' : IDL.Null,
    'small' : IDL.Null,
    'medium' : IDL.Null,
  });
  const RecipeIngredient = IDL.Record({
    'quantity' : Weight,
    'ingredientId' : IDL.Nat,
  });
  const RecipeInput = IDL.Record({
    'name' : IDL.Text,
    'bowlSize' : BowlSize,
    'ingredients' : IDL.Vec(RecipeIngredient),
  });
  const Ingredient = IDL.Record({
    'id' : IDL.Nat,
    'lowStockThreshold' : Weight,
    'supplierName' : IDL.Text,
    'name' : IDL.Text,
    'quantity' : Weight,
    'costPricePerUnit' : IDL.Float64,
  });
  const Recipe = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'bowlSize' : BowlSize,
    'ingredients' : IDL.Vec(RecipeIngredient),
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'updatedAt' : IDL.Int,
    'address' : IDL.Text,
  });
  const InventoryState = IDL.Record({
    'totalValue' : IDL.Float64,
    'ingredients' : IDL.Vec(Ingredient),
  });
  
  return IDL.Service({
    'addCustomer' : IDL.Func([SessionId, CustomerInput], [IDL.Nat], []),
    'addIngredient' : IDL.Func([SessionId, IngredientInput], [], []),
    'addRecipe' : IDL.Func([SessionId, RecipeInput], [], []),
    'createSession' : IDL.Func([], [SessionId], []),
    'deleteCustomer' : IDL.Func([SessionId, IDL.Nat], [], []),
    'endSession' : IDL.Func([SessionId], [], []),
    'getAllIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
    'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
    'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getIngredient' : IDL.Func([IDL.Nat], [IDL.Opt(Ingredient)], ['query']),
    'getInventoryState' : IDL.Func([], [InventoryState], ['query']),
    'getLowStockIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
    'getRecipe' : IDL.Func([IDL.Nat], [IDL.Opt(Recipe)], ['query']),
    'isSessionActive' : IDL.Func([SessionId], [IDL.Bool], ['query']),
    'updateCustomer' : IDL.Func([SessionId, IDL.Nat, CustomerInput], [], []),
    'updateIngredient' : IDL.Func(
        [SessionId, IDL.Nat, IngredientInput],
        [],
        [],
      ),
    'updateRecipe' : IDL.Func([SessionId, IDL.Nat, RecipeInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };