/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BowlSize = { 'large' : null } |
  { 'small' : null } |
  { 'medium' : null };
export interface Ingredient {
  'id' : bigint,
  'lowStockThreshold' : Weight,
  'supplierName' : string,
  'name' : string,
  'quantity' : Weight,
  'costPricePerUnit' : number,
}
export interface IngredientInput {
  'lowStockThreshold' : Weight,
  'supplierName' : string,
  'name' : string,
  'quantity' : Weight,
  'costPricePerUnit' : number,
}
export interface InventoryState {
  'totalValue' : number,
  'ingredients' : Array<Ingredient>,
}
export interface Recipe {
  'id' : bigint,
  'name' : string,
  'bowlSize' : BowlSize,
  'ingredients' : Array<RecipeIngredient>,
}
export interface RecipeIngredient {
  'quantity' : Weight,
  'ingredientId' : bigint,
}
export interface RecipeInput {
  'name' : string,
  'bowlSize' : BowlSize,
  'ingredients' : Array<RecipeIngredient>,
}
export type SessionId = string;
export interface Weight {
  'value' : bigint,
  'unit' : { 'kilograms' : null } |
    { 'grams' : null },
}
export interface _SERVICE {
  'addIngredient' : ActorMethod<[SessionId, IngredientInput], undefined>,
  'addRecipe' : ActorMethod<[SessionId, RecipeInput], undefined>,
  'createSession' : ActorMethod<[], SessionId>,
  'endSession' : ActorMethod<[SessionId], undefined>,
  'getAllIngredients' : ActorMethod<[], Array<Ingredient>>,
  'getAllRecipes' : ActorMethod<[], Array<Recipe>>,
  'getIngredient' : ActorMethod<[bigint], [] | [Ingredient]>,
  'getInventoryState' : ActorMethod<[], InventoryState>,
  'getLowStockIngredients' : ActorMethod<[], Array<Ingredient>>,
  'getRecipe' : ActorMethod<[bigint], [] | [Recipe]>,
  'isSessionActive' : ActorMethod<[SessionId], boolean>,
  'updateIngredient' : ActorMethod<
    [SessionId, bigint, IngredientInput],
    undefined
  >,
  'updateRecipe' : ActorMethod<[SessionId, bigint, RecipeInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];