/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionId = IDL.Text;
export const CustomerInput = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
});
export const Weight = IDL.Record({
  'value' : IDL.Int,
  'unit' : IDL.Variant({ 'kilograms' : IDL.Null, 'grams' : IDL.Null }),
});
export const IngredientInput = IDL.Record({
  'lowStockThreshold' : Weight,
  'supplierName' : IDL.Text,
  'name' : IDL.Text,
  'quantity' : Weight,
  'costPricePerUnit' : IDL.Float64,
});
export const BowlSize = IDL.Variant({
  'large' : IDL.Null,
  'small' : IDL.Null,
  'medium' : IDL.Null,
});
export const RecipeIngredient = IDL.Record({
  'quantity' : Weight,
  'ingredientId' : IDL.Nat,
});
export const RecipeInput = IDL.Record({
  'name' : IDL.Text,
  'bowlSize' : BowlSize,
  'ingredients' : IDL.Vec(RecipeIngredient),
});
export const SubscriptionInput = IDL.Record({
  'paymentStatus' : IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'overdue' : IDL.Null,
  }),
  'endDate' : IDL.Text,
  'customerId' : IDL.Nat,
  'price' : IDL.Float64,
  'planType' : IDL.Variant({
    'weekly6days' : IDL.Null,
    'monthly24days' : IDL.Null,
  }),
  'bowlSize' : BowlSize,
  'startDate' : IDL.Text,
});
export const PaymentMode = IDL.Variant({
  'upi' : IDL.Null,
  'card' : IDL.Null,
  'cash' : IDL.Null,
});
export const InvoiceInputItem = IDL.Record({
  'recipeId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
});
export const InvoiceInput = IDL.Record({
  'invoiceDate' : IDL.Int,
  'discount' : IDL.Float64,
  'paymentMode' : PaymentMode,
  'customerId' : IDL.Opt(IDL.Nat),
  'items' : IDL.Vec(InvoiceInputItem),
});
export const Ingredient = IDL.Record({
  'id' : IDL.Nat,
  'lowStockThreshold' : Weight,
  'supplierName' : IDL.Text,
  'name' : IDL.Text,
  'quantity' : Weight,
  'costPricePerUnit' : IDL.Float64,
});
export const InvoiceItem = IDL.Record({
  'recipeId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
  'totalPrice' : IDL.Float64,
});
export const SalesInvoice = IDL.Record({
  'id' : IDL.Nat,
  'invoiceDate' : IDL.Int,
  'totalAmount' : IDL.Float64,
  'discount' : IDL.Float64,
  'paymentMode' : PaymentMode,
  'customerId' : IDL.Opt(IDL.Nat),
  'items' : IDL.Vec(InvoiceItem),
});
export const Recipe = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'bowlSize' : BowlSize,
  'ingredients' : IDL.Vec(RecipeIngredient),
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'updatedAt' : IDL.Int,
  'address' : IDL.Text,
});
export const Subscription = IDL.Record({
  'id' : IDL.Nat,
  'paymentStatus' : IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'overdue' : IDL.Null,
  }),
  'endDate' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'customerId' : IDL.Nat,
  'price' : IDL.Float64,
  'planType' : IDL.Variant({
    'weekly6days' : IDL.Null,
    'monthly24days' : IDL.Null,
  }),
  'bowlSize' : BowlSize,
  'startDate' : IDL.Text,
});
export const InventoryAdjustment = IDL.Record({
  'timestamp' : IDL.Int,
  'relatedInvoiceId' : IDL.Opt(IDL.Nat),
  'ingredientId' : IDL.Nat,
  'quantityChanged' : Weight,
  'reason' : IDL.Variant({ 'sale' : IDL.Null, 'restock' : IDL.Null }),
});
export const InventoryState = IDL.Record({
  'totalValue' : IDL.Float64,
  'ingredients' : IDL.Vec(Ingredient),
});

export const idlService = IDL.Service({
  'addCustomer' : IDL.Func([SessionId, CustomerInput], [IDL.Nat], []),
  'addIngredient' : IDL.Func([SessionId, IngredientInput], [], []),
  'addRecipe' : IDL.Func([SessionId, RecipeInput], [], []),
  'addSubscription' : IDL.Func([SessionId, SubscriptionInput], [IDL.Nat], []),
  'createInvoice' : IDL.Func([SessionId, InvoiceInput], [IDL.Nat], []),
  'createSession' : IDL.Func([], [SessionId], []),
  'deleteCustomer' : IDL.Func([SessionId, IDL.Nat], [], []),
  'deleteSubscription' : IDL.Func([SessionId, IDL.Nat], [], []),
  'endSession' : IDL.Func([SessionId], [], []),
  'getAllIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(SalesInvoice)], ['query']),
  'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
  'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getExpiringSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
  'getIngredient' : IDL.Func([IDL.Nat], [IDL.Opt(Ingredient)], ['query']),
  'getInventoryAdjustments' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(InventoryAdjustment)],
      ['query'],
    ),
  'getInventoryState' : IDL.Func([], [InventoryState], ['query']),
  'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(SalesInvoice)], ['query']),
  'getInvoicesByCustomer' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SalesInvoice)],
      ['query'],
    ),
  'getLowStockIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
  'getRecipe' : IDL.Func([IDL.Nat], [IDL.Opt(Recipe)], ['query']),
  'getSubscriptions' : IDL.Func(
      [IDL.Opt(IDL.Nat)],
      [IDL.Vec(Subscription)],
      ['query'],
    ),
  'isSessionActive' : IDL.Func([SessionId], [IDL.Bool], ['query']),
  'restockIngredient' : IDL.Func([SessionId, IDL.Nat, Weight], [], []),
  'updateCustomer' : IDL.Func([SessionId, IDL.Nat, CustomerInput], [], []),
  'updateIngredient' : IDL.Func([SessionId, IDL.Nat, IngredientInput], [], []),
  'updateRecipe' : IDL.Func([SessionId, IDL.Nat, RecipeInput], [], []),
  'updateSubscription' : IDL.Func(
      [SessionId, IDL.Nat, SubscriptionInput],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionId = IDL.Text;
  const CustomerInput = IDL.Record({
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
  });
  const Weight = IDL.Record({
    'value' : IDL.Int,
    'unit' : IDL.Variant({ 'kilograms' : IDL.Null, 'grams' : IDL.Null }),
  });
  const IngredientInput = IDL.Record({
    'lowStockThreshold' : Weight,
    'supplierName' : IDL.Text,
    'name' : IDL.Text,
    'quantity' : Weight,
    'costPricePerUnit' : IDL.Float64,
  });
  const BowlSize = IDL.Variant({
    'large' : IDL.Null,
    'small' : IDL.Null,
    'medium' : IDL.Null,
  });
  const RecipeIngredient = IDL.Record({
    'quantity' : Weight,
    'ingredientId' : IDL.Nat,
  });
  const RecipeInput = IDL.Record({
    'name' : IDL.Text,
    'bowlSize' : BowlSize,
    'ingredients' : IDL.Vec(RecipeIngredient),
  });
  const SubscriptionInput = IDL.Record({
    'paymentStatus' : IDL.Variant({
      'cancelled' : IDL.Null,
      'pending' : IDL.Null,
      'paid' : IDL.Null,
      'overdue' : IDL.Null,
    }),
    'endDate' : IDL.Text,
    'customerId' : IDL.Nat,
    'price' : IDL.Float64,
    'planType' : IDL.Variant({
      'weekly6days' : IDL.Null,
      'monthly24days' : IDL.Null,
    }),
    'bowlSize' : BowlSize,
    'startDate' : IDL.Text,
  });
  const PaymentMode = IDL.Variant({
    'upi' : IDL.Null,
    'card' : IDL.Null,
    'cash' : IDL.Null,
  });
  const InvoiceInputItem = IDL.Record({
    'recipeId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
  });
  const InvoiceInput = IDL.Record({
    'invoiceDate' : IDL.Int,
    'discount' : IDL.Float64,
    'paymentMode' : PaymentMode,
    'customerId' : IDL.Opt(IDL.Nat),
    'items' : IDL.Vec(InvoiceInputItem),
  });
  const Ingredient = IDL.Record({
    'id' : IDL.Nat,
    'lowStockThreshold' : Weight,
    'supplierName' : IDL.Text,
    'name' : IDL.Text,
    'quantity' : Weight,
    'costPricePerUnit' : IDL.Float64,
  });
  const InvoiceItem = IDL.Record({
    'recipeId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
    'totalPrice' : IDL.Float64,
  });
  const SalesInvoice = IDL.Record({
    'id' : IDL.Nat,
    'invoiceDate' : IDL.Int,
    'totalAmount' : IDL.Float64,
    'discount' : IDL.Float64,
    'paymentMode' : PaymentMode,
    'customerId' : IDL.Opt(IDL.Nat),
    'items' : IDL.Vec(InvoiceItem),
  });
  const Recipe = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'bowlSize' : BowlSize,
    'ingredients' : IDL.Vec(RecipeIngredient),
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'updatedAt' : IDL.Int,
    'address' : IDL.Text,
  });
  const Subscription = IDL.Record({
    'id' : IDL.Nat,
    'paymentStatus' : IDL.Variant({
      'cancelled' : IDL.Null,
      'pending' : IDL.Null,
      'paid' : IDL.Null,
      'overdue' : IDL.Null,
    }),
    'endDate' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'customerId' : IDL.Nat,
    'price' : IDL.Float64,
    'planType' : IDL.Variant({
      'weekly6days' : IDL.Null,
      'monthly24days' : IDL.Null,
    }),
    'bowlSize' : BowlSize,
    'startDate' : IDL.Text,
  });
  const InventoryAdjustment = IDL.Record({
    'timestamp' : IDL.Int,
    'relatedInvoiceId' : IDL.Opt(IDL.Nat),
    'ingredientId' : IDL.Nat,
    'quantityChanged' : Weight,
    'reason' : IDL.Variant({ 'sale' : IDL.Null, 'restock' : IDL.Null }),
  });
  const InventoryState = IDL.Record({
    'totalValue' : IDL.Float64,
    'ingredients' : IDL.Vec(Ingredient),
  });
  
  return IDL.Service({
    'addCustomer' : IDL.Func([SessionId, CustomerInput], [IDL.Nat], []),
    'addIngredient' : IDL.Func([SessionId, IngredientInput], [], []),
    'addRecipe' : IDL.Func([SessionId, RecipeInput], [], []),
    'addSubscription' : IDL.Func([SessionId, SubscriptionInput], [IDL.Nat], []),
    'createInvoice' : IDL.Func([SessionId, InvoiceInput], [IDL.Nat], []),
    'createSession' : IDL.Func([], [SessionId], []),
    'deleteCustomer' : IDL.Func([SessionId, IDL.Nat], [], []),
    'deleteSubscription' : IDL.Func([SessionId, IDL.Nat], [], []),
    'endSession' : IDL.Func([SessionId], [], []),
    'getAllIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(SalesInvoice)], ['query']),
    'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
    'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getExpiringSubscriptions' : IDL.Func(
        [],
        [IDL.Vec(Subscription)],
        ['query'],
      ),
    'getIngredient' : IDL.Func([IDL.Nat], [IDL.Opt(Ingredient)], ['query']),
    'getInventoryAdjustments' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(InventoryAdjustment)],
        ['query'],
      ),
    'getInventoryState' : IDL.Func([], [InventoryState], ['query']),
    'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(SalesInvoice)], ['query']),
    'getInvoicesByCustomer' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SalesInvoice)],
        ['query'],
      ),
    'getLowStockIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
    'getRecipe' : IDL.Func([IDL.Nat], [IDL.Opt(Recipe)], ['query']),
    'getSubscriptions' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(Subscription)],
        ['query'],
      ),
    'isSessionActive' : IDL.Func([SessionId], [IDL.Bool], ['query']),
    'restockIngredient' : IDL.Func([SessionId, IDL.Nat, Weight], [], []),
    'updateCustomer' : IDL.Func([SessionId, IDL.Nat, CustomerInput], [], []),
    'updateIngredient' : IDL.Func(
        [SessionId, IDL.Nat, IngredientInput],
        [],
        [],
      ),
    'updateRecipe' : IDL.Func([SessionId, IDL.Nat, RecipeInput], [], []),
    'updateSubscription' : IDL.Func(
        [SessionId, IDL.Nat, SubscriptionInput],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };