/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer {
  'id' : bigint,
  'contactInfo' : string,
  'name' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'updatedAt' : bigint,
  'address' : string,
}
export interface CustomerInput {
  'contactInfo' : string,
  'name' : string,
  'address' : string,
}
export interface Ingredient {
  'id' : bigint,
  'lowStockThreshold' : Weight,
  'supplierName' : string,
  'name' : string,
  'quantity' : Weight,
  'costPricePerUnit' : number,
}
export interface IngredientInput {
  'lowStockThreshold' : Weight,
  'supplierName' : string,
  'name' : string,
  'quantity' : Weight,
  'costPricePerUnit' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Weight {
  'value' : number,
  'unit' : { 'kilograms' : null } |
    { 'grams' : null },
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCustomer' : ActorMethod<[CustomerInput], bigint>,
  'createIngredient' : ActorMethod<[IngredientInput], bigint>,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'deleteIngredient' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomers' : ActorMethod<[], Array<Customer>>,
  'getIngredients' : ActorMethod<[], Array<Ingredient>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCustomer' : ActorMethod<[bigint, CustomerInput], undefined>,
  'updateIngredient' : ActorMethod<[bigint, IngredientInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];