/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CustomerInput = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
});
export const Weight = IDL.Record({
  'value' : IDL.Float64,
  'unit' : IDL.Variant({ 'kilograms' : IDL.Null, 'grams' : IDL.Null }),
});
export const IngredientInput = IDL.Record({
  'lowStockThreshold' : Weight,
  'supplierName' : IDL.Text,
  'name' : IDL.Text,
  'quantity' : Weight,
  'costPricePerUnit' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'updatedAt' : IDL.Int,
  'address' : IDL.Text,
});
export const Ingredient = IDL.Record({
  'id' : IDL.Nat,
  'lowStockThreshold' : Weight,
  'supplierName' : IDL.Text,
  'name' : IDL.Text,
  'quantity' : Weight,
  'costPricePerUnit' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCustomer' : IDL.Func([CustomerInput], [IDL.Nat], []),
  'createIngredient' : IDL.Func([IngredientInput], [IDL.Nat], []),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'deleteIngredient' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCustomer' : IDL.Func([IDL.Nat, CustomerInput], [], []),
  'updateIngredient' : IDL.Func([IDL.Nat, IngredientInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CustomerInput = IDL.Record({
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
  });
  const Weight = IDL.Record({
    'value' : IDL.Float64,
    'unit' : IDL.Variant({ 'kilograms' : IDL.Null, 'grams' : IDL.Null }),
  });
  const IngredientInput = IDL.Record({
    'lowStockThreshold' : Weight,
    'supplierName' : IDL.Text,
    'name' : IDL.Text,
    'quantity' : Weight,
    'costPricePerUnit' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'updatedAt' : IDL.Int,
    'address' : IDL.Text,
  });
  const Ingredient = IDL.Record({
    'id' : IDL.Nat,
    'lowStockThreshold' : Weight,
    'supplierName' : IDL.Text,
    'name' : IDL.Text,
    'quantity' : Weight,
    'costPricePerUnit' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCustomer' : IDL.Func([CustomerInput], [IDL.Nat], []),
    'createIngredient' : IDL.Func([IngredientInput], [IDL.Nat], []),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'deleteIngredient' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCustomer' : IDL.Func([IDL.Nat, CustomerInput], [], []),
    'updateIngredient' : IDL.Func([IDL.Nat, IngredientInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };