/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface IngredientInput {
    lowStockThreshold: Weight;
    supplierName: string;
    name: string;
    quantity: Weight;
    costPricePerUnit: number;
}
export interface Weight {
    value: bigint;
    unit: Variant_kilograms_grams;
}
export interface RecipeInput {
    name: string;
    bowlSize: BowlSize;
    ingredients: Array<RecipeIngredient>;
}
export interface Ingredient {
    id: bigint;
    lowStockThreshold: Weight;
    supplierName: string;
    name: string;
    quantity: Weight;
    costPricePerUnit: number;
}
export interface InventoryState {
    totalValue: number;
    ingredients: Array<Ingredient>;
}
export type SessionId = string;
export interface Recipe {
    id: bigint;
    name: string;
    bowlSize: BowlSize;
    ingredients: Array<RecipeIngredient>;
}
export interface RecipeIngredient {
    quantity: Weight;
    ingredientId: bigint;
}
export enum BowlSize {
    large = "large",
    small = "small",
    medium = "medium"
}
export enum Variant_kilograms_grams {
    kilograms = "kilograms",
    grams = "grams"
}
export interface backendInterface {
    addIngredient(sessionId: SessionId, ingredient: IngredientInput): Promise<void>;
    addRecipe(sessionId: SessionId, recipe: RecipeInput): Promise<void>;
    createSession(): Promise<SessionId>;
    endSession(sessionId: SessionId): Promise<void>;
    getAllIngredients(): Promise<Array<Ingredient>>;
    getAllRecipes(): Promise<Array<Recipe>>;
    getIngredient(ingredientId: bigint): Promise<Ingredient | null>;
    getInventoryState(): Promise<InventoryState>;
    getLowStockIngredients(): Promise<Array<Ingredient>>;
    getRecipe(recipeId: bigint): Promise<Recipe | null>;
    isSessionActive(sessionId: SessionId): Promise<boolean>;
    updateIngredient(sessionId: SessionId, ingredientId: bigint, updatedIngredient: IngredientInput): Promise<void>;
    updateRecipe(sessionId: SessionId, recipeId: bigint, updatedRecipe: RecipeInput): Promise<void>;
}
import type { BowlSize as _BowlSize, Ingredient as _Ingredient, IngredientInput as _IngredientInput, InventoryState as _InventoryState, Recipe as _Recipe, RecipeIngredient as _RecipeIngredient, RecipeInput as _RecipeInput, Weight as _Weight } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addIngredient(arg0: SessionId, arg1: IngredientInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addIngredient(arg0, to_candid_IngredientInput_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIngredient(arg0, to_candid_IngredientInput_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addRecipe(arg0: SessionId, arg1: RecipeInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRecipe(arg0, to_candid_RecipeInput_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRecipe(arg0, to_candid_RecipeInput_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createSession(): Promise<SessionId> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession();
            return result;
        }
    }
    async endSession(arg0: SessionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endSession(arg0);
            return result;
        }
    }
    async getAllIngredients(): Promise<Array<Ingredient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIngredients();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIngredients();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRecipes(): Promise<Array<Recipe>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecipes();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecipes();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIngredient(arg0: bigint): Promise<Ingredient | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getIngredient(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIngredient(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInventoryState(): Promise<InventoryState> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryState();
                return from_candid_InventoryState_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryState();
            return from_candid_InventoryState_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLowStockIngredients(): Promise<Array<Ingredient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockIngredients();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockIngredients();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecipe(arg0: bigint): Promise<Recipe | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecipe(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecipe(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async isSessionActive(arg0: SessionId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isSessionActive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isSessionActive(arg0);
            return result;
        }
    }
    async updateIngredient(arg0: SessionId, arg1: bigint, arg2: IngredientInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIngredient(arg0, arg1, to_candid_IngredientInput_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIngredient(arg0, arg1, to_candid_IngredientInput_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateRecipe(arg0: SessionId, arg1: bigint, arg2: RecipeInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRecipe(arg0, arg1, to_candid_RecipeInput_n6(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRecipe(arg0, arg1, to_candid_RecipeInput_n6(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_BowlSize_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BowlSize): BowlSize {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Ingredient_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ingredient): Ingredient {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_InventoryState_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryState): InventoryState {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_RecipeIngredient_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecipeIngredient): RecipeIngredient {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Recipe_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Recipe): Recipe {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Weight_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Weight): Weight {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Ingredient]): Ingredient | null {
    return value.length === 0 ? null : from_candid_Ingredient_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Recipe]): Recipe | null {
    return value.length === 0 ? null : from_candid_Recipe_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    lowStockThreshold: _Weight;
    supplierName: string;
    name: string;
    quantity: _Weight;
    costPricePerUnit: number;
}): {
    id: bigint;
    lowStockThreshold: Weight;
    supplierName: string;
    name: string;
    quantity: Weight;
    costPricePerUnit: number;
} {
    return {
        id: value.id,
        lowStockThreshold: from_candid_Weight_n16(_uploadFile, _downloadFile, value.lowStockThreshold),
        supplierName: value.supplierName,
        name: value.name,
        quantity: from_candid_Weight_n16(_uploadFile, _downloadFile, value.quantity),
        costPricePerUnit: value.costPricePerUnit
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: bigint;
    unit: {
        kilograms: null;
    } | {
        grams: null;
    };
}): {
    value: bigint;
    unit: Variant_kilograms_grams;
} {
    return {
        value: value.value,
        unit: from_candid_variant_n18(_uploadFile, _downloadFile, value.unit)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    bowlSize: _BowlSize;
    ingredients: Array<_RecipeIngredient>;
}): {
    id: bigint;
    name: string;
    bowlSize: BowlSize;
    ingredients: Array<RecipeIngredient>;
} {
    return {
        id: value.id,
        name: value.name,
        bowlSize: from_candid_BowlSize_n22(_uploadFile, _downloadFile, value.bowlSize),
        ingredients: from_candid_vec_n24(_uploadFile, _downloadFile, value.ingredients)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    quantity: _Weight;
    ingredientId: bigint;
}): {
    quantity: Weight;
    ingredientId: bigint;
} {
    return {
        quantity: from_candid_Weight_n16(_uploadFile, _downloadFile, value.quantity),
        ingredientId: value.ingredientId
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalValue: number;
    ingredients: Array<_Ingredient>;
}): {
    totalValue: number;
    ingredients: Array<Ingredient>;
} {
    return {
        totalValue: value.totalValue,
        ingredients: from_candid_vec_n13(_uploadFile, _downloadFile, value.ingredients)
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kilograms: null;
} | {
    grams: null;
}): Variant_kilograms_grams {
    return "kilograms" in value ? Variant_kilograms_grams.kilograms : "grams" in value ? Variant_kilograms_grams.grams : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    large: null;
} | {
    small: null;
} | {
    medium: null;
}): BowlSize {
    return "large" in value ? BowlSize.large : "small" in value ? BowlSize.small : "medium" in value ? BowlSize.medium : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ingredient>): Array<Ingredient> {
    return value.map((x)=>from_candid_Ingredient_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Recipe>): Array<Recipe> {
    return value.map((x)=>from_candid_Recipe_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RecipeIngredient>): Array<RecipeIngredient> {
    return value.map((x)=>from_candid_RecipeIngredient_n25(_uploadFile, _downloadFile, x));
}
function to_candid_BowlSize_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BowlSize): _BowlSize {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_IngredientInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IngredientInput): _IngredientInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_RecipeIngredient_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecipeIngredient): _RecipeIngredient {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_RecipeInput_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecipeInput): _RecipeInput {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_Weight_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Weight): _Weight {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    quantity: Weight;
    ingredientId: bigint;
}): {
    quantity: _Weight;
    ingredientId: bigint;
} {
    return {
        quantity: to_candid_Weight_n3(_uploadFile, _downloadFile, value.quantity),
        ingredientId: value.ingredientId
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lowStockThreshold: Weight;
    supplierName: string;
    name: string;
    quantity: Weight;
    costPricePerUnit: number;
}): {
    lowStockThreshold: _Weight;
    supplierName: string;
    name: string;
    quantity: _Weight;
    costPricePerUnit: number;
} {
    return {
        lowStockThreshold: to_candid_Weight_n3(_uploadFile, _downloadFile, value.lowStockThreshold),
        supplierName: value.supplierName,
        name: value.name,
        quantity: to_candid_Weight_n3(_uploadFile, _downloadFile, value.quantity),
        costPricePerUnit: value.costPricePerUnit
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: bigint;
    unit: Variant_kilograms_grams;
}): {
    value: bigint;
    unit: {
        kilograms: null;
    } | {
        grams: null;
    };
} {
    return {
        value: value.value,
        unit: to_candid_variant_n5(_uploadFile, _downloadFile, value.unit)
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    bowlSize: BowlSize;
    ingredients: Array<RecipeIngredient>;
}): {
    name: string;
    bowlSize: _BowlSize;
    ingredients: Array<_RecipeIngredient>;
} {
    return {
        name: value.name,
        bowlSize: to_candid_BowlSize_n8(_uploadFile, _downloadFile, value.bowlSize),
        ingredients: to_candid_vec_n10(_uploadFile, _downloadFile, value.ingredients)
    };
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_kilograms_grams): {
    kilograms: null;
} | {
    grams: null;
} {
    return value == Variant_kilograms_grams.kilograms ? {
        kilograms: null
    } : value == Variant_kilograms_grams.grams ? {
        grams: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BowlSize): {
    large: null;
} | {
    small: null;
} | {
    medium: null;
} {
    return value == BowlSize.large ? {
        large: null
    } : value == BowlSize.small ? {
        small: null
    } : value == BowlSize.medium ? {
        medium: null
    } : value;
}
function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<RecipeIngredient>): Array<_RecipeIngredient> {
    return value.map((x)=>to_candid_RecipeIngredient_n11(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
